<a href="https://colab.research.google.com/github/digdemorhan/Tensorflow_Ecosystem/blob/main/TensorflowTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.1


In [5]:
#0 boyutlu tensor oluşturmak
scalar = tf.constant(3)
print("Tensor:", scalar)
print("Tensor boyutu:", scalar.ndim)

Tensor: tf.Tensor(3, shape=(), dtype=int32)
Tensor boyutu: 0


In [7]:
#Vector oluşturmak
vector = tf.constant([1,2])
print("Vector:", vector)
print("Vector boyutu:", vector.ndim)

Vector: tf.Tensor([1 2], shape=(2,), dtype=int32)
Vector boyutu: 1


In [8]:
#Matrix oluşturmak
matrix = tf.constant([[1,2],[3,4]])
print("Matrix:", matrix)
print("Matrix boyutu:", matrix.ndim)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Matrix boyutu: 2


In [9]:
#MNIST veri seti üzerinde bir inceleme
from tensorflow.keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [10]:
#Eğitim verisinin boyutu
train_images.ndim

3

In [11]:
#Eğitim verisinin shape'i
train_images.shape

(60000, 28, 28)

In [12]:
#Eğitim verisinin veri tipi
train_images.dtype

dtype('uint8')

In [13]:
#Variable ile tensor oluşturmak
v = tf.Variable([1,2])
c = tf.constant([1,2])
v,c

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

**variable ile oluşturulan tensor -> mutable (değiştirilebilir)**

**constant ile oluşturulan tensor -> immutable (değiştirilemez)**

In [14]:
#Assign metodu ile v tensorunun değerini değiştirmek
v[0].assign(7)
v

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

In [20]:
#Rastgele tensor oluşturmak
tf.random.set_seed(42)
tf.random.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519],
       [-2.3880599, -1.0392479]], dtype=float32)>

In [23]:
#1'ler ve 0'lardan oluşan tensor üretmek
print(tf.ones(shape=[3,2]))
print()
print(tf.zeros(shape=[3,2]))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [29]:
#Numpy array'leri tensorlere çevirmek
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
print(numpy_A)
tensor_A = tf.constant(numpy_A,shape=[2,4,3])
print(tensor_A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)


In [33]:
#Tensor'leri dilimlemek
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
#Tensor boyutunu değiştirmek
rank_5_tensor = rank_4_tensor[..., tf.newaxis]
rank_5_tensor.ndim

5

In [38]:
print(rank_4_tensor.shape)
print(rank_5_tensor.shape)

(2, 3, 4, 5)
(2, 3, 4, 5, 1)


In [39]:
#Tensor boyutunu arttırmak için expand_dims metodunu kullanmak
rank_6_tensor = tf.expand_dims(rank_5_tensor, axis=-1)
rank_6_tensor.shape

TensorShape([2, 3, 4, 5, 1, 1])

In [42]:
#Tensor işlemleri
tensor = tf.constant([[1,2],[3,4]])
print(tensor)
print()
print(tensor+10)
print()
print(tensor-10)
print()
print(tensor*10)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [46]:
#Tensorflow fonksiyonlarıya tensor işlemleri
print(tf.multiply(tensor,10))
print()
print(tf.matmul(tensor, tensor)) #matmul ile matris çarpımı
print()
print(tensor @ tensor) #@ ile matris çarpımı
print()

tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)



In [51]:
#Matrix boyutunu değiştirmek
tensor = tf.constant([[1,2,3],[4,5,6]])
print(tensor)
print()
tensor_new = tf.reshape(tensor, shape=(3,2))
print(tensor_new)
print()
tensor_transpose = tf.transpose(tensor)
print(tensor_transpose)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [54]:
#Tensor'un veri tipini değiştirmek
tensor = tf.constant([1.2,3.4])
print(tensor)
tensor_cast = tf.cast(tensor, dtype=tf.float16)
print(tensor_cast)

tf.Tensor([1.2 3.4], shape=(2,), dtype=float32)
tf.Tensor([1.2 3.4], shape=(2,), dtype=float16)


In [57]:
#Squeezed metodu ile tensordeki 1 boyutlarını kaldırmak
tensor = tf.constant(np.random.randint(0,100,50), shape=(1,1,1,1,50))
print(tensor.shape)
print()
tensor_squeezed = tf.squeeze(tensor)
print(tensor_squeezed.shape)

(1, 1, 1, 1, 50)

(50,)


In [58]:
#Tensorflow ile one-hot kodlama
data = [0,1,2,3]
tf.one_hot(data, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [62]:
#Tensorflow dekoratör
@tf.function
def f(x):
  return x**2

data = tf.constant(np.arange(0,10))
f(data)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

**Dekoratörler, metotların davranışlarını değiştirir.**

In [65]:
#Makinedeki GPU kontrolü
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]